### ISSUE TITLE
도형을 겹쳐서 그리는 경우 교차하는 영역이 일부 지워짐

### ISSUE THREAD

**Issue by xellnaga** [Pseudo-Lab/AC_Innovative_Drawing_Board#7]
캔버스에 그리는 모든 도형을 리스트에 저장하고,
새로 도형을 추가할 때 마다 리스트에 저장된 도형들을 다시 그려주는 방식을 고려해야할 듯.

**Comment by sungminYoon** [comment]
Guide scene 추가 하여
그리기시 잔상 문제
영영이 일부 지워짐 문제
이미지 에 그리기 남는 문제
해결 했습니다. ㅎ

**Comment by xellnaga** [comment]
문제해결확인
